### PR TITLE
Update conda recipe for vtk 9.1/ITK 5

### PR DESCRIPTION
**Pull request by ramtingh**
This should fix the CI and conda packaging system to work with VTK 9.1, ITK 5 and python 3.7+. 
I've only added linux and windows builds, while in theory appveyor supports OS X I don't have enough experience to figure what is going wrong with the OS X builds, so I think it makes more sense to focus on linux and windows first and If I get around to investigating OS X issues I'll open another pull request.

### CODE REVIEW

**Comment by lassoan** [comment]
@ramtingh I've rebased this branch based on the latest master. It would be great if you could finalize it to work with VTK-9 and Python 3.7+. Thank you!

**Comment by ramtingh** [comment]
@lassoan Thanks, I should be able to get to this soon. Currently the compilation, packaging and tests work fine for linux [https://ci.appveyor.com/project/rlizzo/vmtk-bh6uc/builds/42102386](https://ci.appveyor.com/project/rlizzo/vmtk-bh6uc/builds/42102386) but the windows version needs some work packaging the built library correctly.

**Comment by ramtingh** [comment]
@lassoan I've rebased this based on the master branch again and verified that it works for windows/linux, python 3.7-3.9 (I don't see a reason it wouldn't work for 3.10, but not all the dependencies  have been updated for 3.10 on conda-forge yet)

Just to double check, based on https://github.com/vmtk/vmtk/commit/bf0748b8f54c0b17c85303f393524d8490d1d253 I'm assuming backwards compatibility with ITK 4 isn't required? I've [updated ](https://github.com/vmtk/vmtk/pull/398/commits/7d65c80ce7f2df0298c765eff2770570f7ceab8d) some references to itkMultiThreader which I'll have to wrap in `if ITK_VERSION_MAJOR` directives if keeping compatibility with ITK 4.

In the interest of builds not taking 4 hours, I've only added python 3.7 and 3.8 for regular CI builds, others can be added by modifying `appveyor.yml` in the root of the repository.  

The conda packages are can be downloaded from the build if anyone wants to use them, e.g. https://ci.appveyor.com/project/rlizzo/vmtk-bh6uc/builds/42238972/job/xxgtpraifhb9mtey/artifacts

**Comment by ramtingh** [comment]
Actually the python 3.10 issues seemed to have been accidentally over-constrained numpy, should be fixed now. Commits with "[ci all]" included in the message trigger a build for 3.7,3.8,3.9 and 3.10 otherwise only 3.7 and 3.8 are built. Let me know if I should change this behavior.

**Comment by lassoan** [comment]
Thank you very much, this is now merged! 🎉 
It is great to see CI passing again.

**Pull request merged**
