### PR TITLE
removed problem python wrapping modules from vtk wrapping

### PR DESCRIPTION
**Pull request by rlizzo**
test for slicer extension fix.

### CODE REVIEW

**Comment by lassoan** [comment]
Thank you.

It should work, but I'll confirm tomorrow morning when the nightly dashboard build results are available.

**Comment by jcfr** [comment]
Can this be merged ? 

@lassoan  This is what is causing build error and prevent the associated extension from building.

**Comment by lassoan** [comment]
Yes, it works well on Windows and at least it's built correctly on Linux. (there is a Mac build error due to some recent changes in Slicer, but we'll fix that in Slicer)

**Comment by rlizzo** [comment]
Thanks @lassoan. Merged

**Pull request merged**
