### PR TITLE
Update Superbuild to VTK 9.1.0

### PR DESCRIPTION
**Pull request by kayarre**
During the investigation of #393 using the latest `vtk 9.1.0` release.

Implemented the following:
- Update superbuild to `vtk 9.1.0`
- Added `#include <cmath> and `std::` references where operators not found. fixes errors like

```
~/vmtk_main/vtkVmtk/DifferentialGeometry/vtkvmtkDoubleVector.cxx:117:12: error: ‘sqrt’ was not declared in this scope
  117 |     norm = sqrt(norm);
```

- RequestData does not appear to be a part of legacy VTK IO? Therefore converted to ProcessRequest (not sure if this is correct). I searched in VTK for some reference to identify a deprecation but couldn't find much. Might make more sense to remove those classes? I don't know who uses them.  Fixes errors like

```
In file included from /home/sansomk/build/vmtk/vmtk_main/vtkVmtk/IO/vtkvmtkXdaReader.cxx:24:
~/vmtk_main/vtkVmtk/IO/vtkvmtkXdaReader.h:50:7: error: ‘int
vtkvmtkXdaReader::RequestData(vtkInformation*, vtkInformationVector**, vtkInformationVector*)’
marked ‘override’,but does not override
   50 |   int RequestData(vtkInformation *, vtkInformationVector **, vtkInformationVector *) override;

```

- add additional test data and update tests for `vmtksurfacebooleanoperation` due to some difference in the output from `vtk 9.1.0`, additional test data is here [vmtk-test-data/pull/3](https://github.com/vmtk/vmtk-test-data/pull/3)

### CODE REVIEW

**Comment by lassoan** [comment]
> * RequestData does not appear to be a part of legacy VTK IO? Therefore converted to ProcessRequest (not sure if this is correct). I searched in VTK for some reference to identify a deprecation but couldn't find much. Might make more sense to remove those classes? I don't know who uses them.  Fixes errors like

See this pull request how dozens of classes were updated:

https://github.com/Kitware/VTK/commit/e9bc920dada7e46a3439792f3e40eddb9967f827

It seems that ReadMeshSimple is used instead of RequestData in many cases.

**Comment by kayarre** [comment]
Thank you @lassoan, that is super helpful. I was looking for quite some time.

**Comment by kayarre** [comment]
@lassoan I updated the affected reader to use `ReadMeshSimple`. This appears to make sense.  Although as I am writing this I am realizing I need to check if still compiles with the previous VTK releases.

I also updated the surface boolean tests to reflect the changes and commit message in the naming from the data repo.

**Comment by kayarre** [comment]
@lassoan What do you think about the updates to the file readers? [aeff4032025bd2632b37b0fe87d1bede6f818c1f](https://github.com/vmtk/vmtk/pull/397/commits/aeff4032025bd2632b37b0fe87d1bede6f818c1f)

**Comment by kayarre** [comment]
Any specific reason to NOT put it in its own file `vtkvmtkITKVersion.h`

**Comment by kayarre** [comment]
@lassoan or @jcfr do you have any thoughts on this solution?

**Comment by kayarre** [comment]
per [vmtk-test-data/pull/3](https://github.com/vmtk/vmtk-test-data/pull/3) this is ready for review or merging.

**Review by lassoan — APPROVED** [review]
Thank you, it looks good to me (the changes look like those that were made in VTK for similar classes).

**Comment by lassoan** [comment]
@kayarre could you resolve the reported conflicts (tests/vmtk-test-data)? Thank you!

**Comment by kayarre** [comment]
Thank you @lassoan, took me longer than expected, but got the issue resolved.

**Comment by kayarre** [comment]
@lassoan this good now?

**Review by lassoan — APPROVED** [review]
Looks good, thank your very much.

**Pull request merged**
