### PR TITLE
Fix python wrapping with vtk9

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @mschumak

**Comment by jcfr** [comment]
I keep getting error complaining that `pytest` is missing ... would be great if someone with more experience with conda and conda-forge could help

Despite of being listed as a test requirements, `pytest` is not installed as it use to be. See [here](https://ci.appveyor.com/project/rlizzo/vmtk-bh6uc/build/1.0.227/job/5kx5skmqxus6svl6#L2849) for the last successful build ... 

```
(C:\Python36_64\conda-bld\vmtk_1531887734895\_test_env) C:\Python36_64\conda-bld\vmtk_1531887734895\test_tmp>pytest ./build/tests/ 
'pytest' is not recognized as an internal or external command,
operable program or batch file.
```

```
+pytest ./build/tests/
/home/travis/miniconda/conda-bld/vmtk_1531886575246/test_tmp/run_test.sh: line 7: pytest: command not found
```

**Comment by jcfr** [comment]
@msarahan Would be great to have your input for these two questions:

* Despite of having `pytest` has a test requirement, tests associated with this project are failing with message like `pytest: command not found`. 
  * This seems to be a new behavior as  the test were [passing](https://ci.appveyor.com/project/rlizzo/vmtk-bh6uc/build/1.0.227/job/5kx5skmqxus6svl6#L2849) and the recipe didn't (seem to have) changed beside of downloading the latest version of miniconda and related build tool.
  * Any idea on what is missing ?

* I was wondering if the approach implemented in this repo follows the "best practice" or if there was a better approach. Seems that (1) there is a lot of duplicated code and (2) the recipe is not managed in a regular feedstock and doesn't benefit from conda-smithy.

**Comment by jcfr** [comment]
Cc: @lantiga @rlizzo

**Comment by msarahan** [comment]
It definitely looks like a bug where the test/requires field in meta.yaml is not being respected somehow.  It does not show up when conda creates that test environment.  I can't tell which version of conda-build is in use.  It looks fairly recent.

**Comment by msarahan** [comment]
could not reproduce with this:

```
package:
  name: pytest_test
  version: 1.0

requirements:
  host:
    - python
  run:
    - python

test:
  requires:
    - pytest
  commands:
    - pytest -h
```

so it's not something fundamentally wrong.  Something more subtle.  Please keep me posted if you're able to isolate it more.

**Comment by jcfr** [comment]
> . Please keep me posted if you're able to isolate it more.

I was able to build the example you provided using `conda build ./distribution`

Now, if I pass `conda build --no-copy-test-source-files ./distribution` like it is done in both [.travis.yml#L76](https://github.com/vmtk/vmtk/blob/94d2789a8cd22197352e25e1d65e4644d751e870/.travis.yml#L76) and [appveyor.yml#L81](https://github.com/vmtk/vmtk/blob/94d2789a8cd22197352e25e1d65e4644d751e870/appveyor.yml#L81), I get the same `pytest: command not found`

Reading the [conda-build doc](https://conda.io/docs/commands/build/conda-build.html), it doesn't seem to indicated that test requirement will not be installed:

```
       --no-copy-test-source-files
              Disables copying the files necessary  for  testing  the  package
              into  the  info/test  folder. Passing this argument means it may
              not be possible to test the  package  without  internet  access.
              There is also a danger that the source archive(s) containing the
              files could become unavailable sometime in the future.
```

Also worth noting that the vmtk folks had that flag for now 6 months.

### Info

```
$ conda-build --version 
conda-build 3.10.9
```

### Step to reproduce

1) Create directory with a file named `meta.yaml` with content described in https://github.com/vmtk/vmtk/pull/313#issuecomment-406139827

For example: `/tmp/test-conda/meta.yaml`

2) From that directory, start a bash within `continuumio/miniconda3:4.5.4`

```
cd /tmp/test-conda
docker run -ti --rm -v $(pwd):/work continuumio/miniconda3:4.5.4 bash
```

3) Run the following commands:

```
conda install -y conda-build

conda build --no-copy-test-source-files .
```

=> It reports the `pytest: command not found`

**Comment by msarahan** [comment]
Thanks.  I'll play with that flag tomorrow.  Not a common use case, but we should have a test for it obviously.

**Comment by jcfr** [comment]
Look like it broke in `3.10.6`: 
* `conda-build==3.10.5`  -> pytest is installed
* `conda-build==3.10.6`  -> failed with `pytest: command not found`

For the vmtk build, I will explicitly install `conda-build==3.9.2`

**Comment by jcfr** [comment]
@lantiga @rlizzo 

* Test are passing on windows :heavy_check_mark: 
* Test are only failing on unix when building against Python 3.5.1:

image

**Comment by jcfr** [comment]
The remaining failures are independent of the build system improvement  I contributed. 

So that we can update the Slicer extension, would be great if you could move forward with the integration.

For reference, the errors associated this PR reported while running `test_centerline_extraction_surface_with_no_hole(aorta_surface)` tests are the following:

* on Linux (details [here](https://travis-ci.org/vmtk/vmtk/jobs/405864789)): 

```
        # the network topology identifies an the input segment with the "0" id.
        # since we artificially created this segment, we don't want to use the
        # ends of the segment as source/target points of the centerline calculation
>       nodeIndexToIgnore = np.where(cellDataTopology[:,0] == 0)[0][0]
E       IndexError: index 0 is out of bounds for axis 0 with size 0
```

* on macOS (details [here](https://travis-ci.org/vmtk/vmtk/jobs/405864792)):

```
        for loopIdx, cellConnectivityList in enumerate(ad['CellData']['CellPointIds']):
            if loopIdx == nodeIndexToIgnore:
                removeCellStartIdx = cellConnectivityList[0]
                removeCellEndIdx = cellConnectivityList[-1]
                removeCellLength = cellConnectivityList.size
                if (removeCellEndIdx + 1) - removeCellStartIdx != removeCellLength:
                    raise(ValueError)
                continue
            else:
>               rescaledCellConnectivity = np.subtract(cellConnectivityList, removeCellLength, where=cellConnectivityList >= removeCellLength)
E               UnboundLocalError: local variable 'removeCellLength' referenced before assignment
```



Would be great if you could have a look ? Or may be you could re-trigger the CI.

Cc: @mschumak

**Comment by mschumak** [comment]
@jcfr Thanks very much for pursuing this. Also, thanks @msarahan for the condo fix.

**Comment by jcfr** [comment]
Ping @rlizzo @lantiga 

Would be great to move forward and integrate this PR. :smile:

**Comment by lantiga** [comment]
Hey @jcfr, sorry for the late reply and thanks a lot for the fix!
Thanks also for the details on the failing tests.

@rlizzo LGTM I'm going ahead and merge the PR.

**Comment by jcfr** [comment]
Thanks for merging :tada:

**Comment by mschumak** [comment]
Fantastic, thank you!

**Pull request merged**
