### PR TITLE
fix: superbuild finds wrong python for VMTK build

### PR DESCRIPTION
**Pull request by kayarre**
VMTK fails to pickup correct python version for the superbuild.
this commit makes the variables use same ones for VTK super build.

I am open to suggestions if there is a better way, but it is a regular issue that I have where the python version is not picked up in external projects.

### CODE REVIEW

**Comment by kayarre** [comment]
any thoughts on this? @jcfr @lassoan

**Comment by lassoan** [comment]
We recently wanted to issue a similar fix in SimpleITK (see https://github.com/Slicer/Slicer/issues/5498). However, further investigation revealed that the problem is actually due to a bug in VTK (that it does not provide sufficient information for FindPython/FindPython3) and it was fixed here:

https://github.com/Kitware/VTK/commit/e54e756184412aea40c6915ccf31856f29b771d9

Could you please check if backporting this fix makes the problem go away for you?

**Comment by kayarre** [comment]
I will give it a try.

**Comment by kayarre** [comment]
@lassoan I am working on testing this out with `vtk 9.1.0`

if this fixes the issue we should update the superbuild to use `vtk 9.1.0`?

**Comment by kayarre** [comment]
So far it looks like using `vtk 9.1.0` creates some additional errors though it does appear to fix this issue.

**Comment by kayarre** [comment]
Closing this and make a new one with with fixes for `vtk 9.1.0` release

**Pull request closed without merging**
