### PR TITLE
BUG: fixed crash when starting vmtklevelsetsegmentation

### PR DESCRIPTION
**Pull request by dpshamonin**
command:
vmtklevelsetsegmentation -ifile image.vti -ofile level_sets.vti

### CODE REVIEW

**Comment by lantiga** [comment]
Is this working with VTK version 6.x?

**Comment by dpshamonin** [comment]
Yes it works(starts, VTK windows with mage is there), I am going to test segmentation now.

Just minor OpenGLTexture error at the start
 (ERROR: In D:\packages\VTK-6.2.0\src\Rendering\OpenGL\vtkOpenGLTexture.cxx, line 200
vtkOpenGLTexture (000000000555B240): No scalar values found for texture input!
) It is not that important now.

I have both VTK5+vmtk(master) and VTK6+vmtk(vtk6) builds.
Just trying more VTK6 to see how far can I go.

**Comment by dpshamonin** [comment]
I will crash later when clicking seed points. the same happens with vmtkcenterlines, ones you clicked, it will crash VTK6+vmtk(vtk6). In VTK5+vmtk(master) vmtkcenterlines works fine. Was able to complete ParentVesselReconstruction tutorial. The VTK6+vmtk(vtk6) does not go that smooth.

**Comment by lantiga** [comment]
Thank you (couldn't check this earlier)

**Pull request merged**
