### PR TITLE
Update buildsystem to support vtk9 fixes

### PR DESCRIPTION
**Pull request by kayarre**
changes based on @jcfr branch to get it compiling locally. I have not run tests yet.

### CODE REVIEW

**Comment by kayarre** [comment]
I think is a good enough release candidate. I was able to get most of the tests working, disabled some, and updated the test data for others.  I continued to have some issues with how cmake finds python and therefore decided to update the cmake minimum to 3.15 and require python3. 

I also converted the test data repository to git-lfs and added a cmake flag so it won't `submodule init` everytime. 

`vmtkcenterlinesnetwork` has a weird bug that is not deterministic because it randomly picks a CellId to remove. The test was passing everytime until today and then randomly passed and failed.

**Comment by kayarre** [comment]
I was able to fix the upwind image filter. I believe that gets all the tests running  that were expected to pass previously.

It appears there are a bunch of scripts used for the ITK5 migration [ITK5Preparation](https://github.com/InsightSoftwareConsortium/ITK/tree/master/Utilities/ITKv5Preparation) I think these might be worth running. Can someone who has done this give me some hints on using them. 

I think the `vtkvmtkSimplifyVoronoiDiagram` is still broken.
What are the other pieces that still need to be addressed?

**Comment by kayarre** [comment]
@lassoan are these changes in the right direction or not? I don't know when or if i should expect feedback.

**Comment by lassoan** [comment]
Thank you for all your work on this! Your changes look good to me, except I'm not sure if we should introduce submodules. Since github allows storing unlimited amount of test data as release assets and [CMake's ExternalData module](https://cmake.org/cmake/help/latest/module/ExternalData.html) can download these data sets (by setting the release name to the hash algorithm name, such as SHA256; and setting the filename to the hash value), there is no need to use submodules. Renaming file to its hash and uploading to a github release can manual but it is also quite easy to automate, as it is done in this repository: https://github.com/Slicer/SlicerTestingData.

If you are done with your changes then please submit a pull request to https://github.com/jcfr/vmtk/tree/update-buildsystem-to-support-vtk9. @jcfr will review and merge the changes, we'll test on Windows/Linux/macOS, then integrate the branch into VMTK master.

**Comment by kayarre** [comment]
@lassoan thank you so much for the feedback. 

The test data was already a submodule, The difference is that I converted the submodule data to using `git lfs` instead of regular git. That seemed to make sense to me, but I know there are mixed experiences with git lfs usability.

I agree with how it is implemented is not ideal. Should I make an attempt at converting the submodule to using the cmake ExternalData?

I will go ahead and make a merge request to @jcfr.

**Comment by lassoan** [comment]
@kayarre https://github.com/vmtk/vmtk/pull/372 is now merged. I think @jcfr included all your commits, except maybe 2 or so. Please check and either close this pull request and open a new one or rebase this one on the latest master. Thank you!

**Comment by kayarre** [comment]
Awesome! I will take a look early next week.

**Comment by kayarre** [comment]
Extracted relevant changes and put into new commits and merge requests. Closing

**Pull request closed without merging**
