### PR TITLE
Fix #469: Add vtkStandardNewMacro to vtkvmtkCenterlineSplittingAndGroupingFilter

### LINKED ISSUE #469: vtkStandardNewMacro missing from vtkvmtkCenterlineSplittingAndGroupingFilter
VTK-style initialization of vtkvmtkCenterlineSplittingAndGroupingFilter fails to compile:

`vtkSmartPointer<vtkvmtkCenterlineSplittingAndGroupingFilter> filter = vtkSmartPointer<vtkvmtkCenterlineSplittingAndGroupingFilter>::New();`

Adding `vtkStandardNewMacro(vtkvmtkCenterlineSplittingAndGroupingFilter)` to vtkvmtkCenterlineSplittingAndGroupingFilter.cxx should fix the issue.

### PR DESCRIPTION
**Pull request by nmontesg**

### CODE REVIEW

**Comment by lassoan** [comment]
Thank you! Can you confirm that no change was needed in the .h file?

**Comment by nmontesg** [comment]
Correct, no change was needed in the .h file

**Comment by lassoan** [comment]
Thanks for confirming, I'll merge it then.

**Comment by lassoan** [comment]
This change was reverted in https://github.com/vmtk/vmtk/commit/dc4b25b38eba00d8282a51aaa4b1ad5b22dcada3

The change was unnecessary and introduced a build error while attempting to add New() method for an abstract class.

**Pull request merged**
