### PR TITLE
WIP: Marco/rebase fixes

### PR DESCRIPTION
**Pull request by kayarre**
Rebased branch from @marco-fedele and moved new scripts into the contrib directory. 

Changes in other scripts seem minor, but still need to test.

### CODE REVIEW

**Review by lassoan — APPROVED** [review]
Thank you. The changes are extensive, but very valuable, as well as your efforts to bring these all back to upstream VMTK.

Have you contacted @marco-fedele? Would he switch to using this repository if these changes are merged? That would be awesome, because then we would not duplicate all the maintenance efforts.

I would not worry too much about what this specific branch potentially breaks, because we have integrated so many other changes that a thorough test campaign (preferably by automated tests) is needed anyway.

**Comment by kayarre** [comment]
I have yet to try reaching out to @marco-fedele. I was hoping he would see this and respond.

**Comment by marco-fedele** [comment]
Dear Kurt and Andras,

For sure I will use the upstream master! Thanks for your interest in including my new scripts!

I will compile this branch and test my scripts as soon as possible.

Do new scripts need to have automatic tests associated with them?

**Comment by lassoan** [comment]
@marco-fedele thanks for showing up here.

> Do new scripts need to have automatic tests associated with them?

Yes, that would be great. It would help discovering and fixing regressions and serve as good examples.

> If you are interested, additional information about (most of) new scripts can be found in this paper:

Add this as a comment to each of your Python scripts (if you haven't added it already).

**Comment by kayarre** [comment]
@marco-fedele if you want to start from this rebased branch that is fine. I just pushed a pep8 fixup commit.

**Comment by lassoan** [comment]
Can you remind what is the status of this? Is this ready to be merged or anybody wanted to further review/discuss it?

**Comment by marco-fedele** [comment]
> Can you remind what is the status of this? Is this ready to be merged or anybody wanted to further review/discuss it?

Dear @lassoan ,

sorry, but I was busy with other projects and still didn't have time to focus on finalizing this pull request.

I have just created a new (more updated) pull request https://github.com/vmtk/vmtk/pull/419 to replace this one (so I can edit it).

The PR is still in draft state because I have to finish checking if everything works with the new VTK. I hope to find time to finish the final checks / cleaning in the coming weeks.

Also, instead of rebasing the commits (as @kayarre did in this PR) I have kept everything consistent with my fork history, as there are many contributors / students who have cloned my repository, and if that's not a problem, I'd rather avoid local conflicts.

If it is ok for you, we can close this PR and continue with the new one.

**Comment by lassoan** [comment]
Merge commits introduce lots of noise, making it hard to distinguish upstream changes from actual contributions, and if comments are not written very thoroughly then they obscure the change history. Merge commits may also create merge conflicts that are practically impossible to resolve (for example, we would need to manually redo all the changes in the already very large and complex https://github.com/vmtk/vmtk/pull/273 pull request). Therefore, it would be much better if you could rebase your changes on the latest master version.

However, there are a number of merge commits in the history, so it should be tolerable to add some more. But at least merge commits should have very clear, descriptive commit comment, telling what actually happened in the merged branch (comments such as `Merge branch 'master' of github.com:marco-fedele/vmtk` should be avoided). If you would want to avoid rebasing on the latest master, would you be at least open to fixing up the top-level merge commit comments?

**Comment by marco-fedele** [comment]
> Merge commits introduce lots of noise, making it hard to distinguish upstream changes from actual contributions, and if comments are not written very thoroughly then they obscure the change history. Merge commits may also create merge conflicts that are practically impossible to resolve (for example, we would need to manually redo all the changes in the already very large and complex #273 pull request). Therefore, it would be much better if you could rebase your changes on the latest master version.
> 
> However, there are a number of merge commits in the history, so it should be tolerable to add some more. But at least merge commits should have very clear, descriptive commit comment, telling what actually happened in the merged branch (comments such as `Merge branch 'master' of github.com:marco-fedele/vmtk` should be avoided). If you would want to avoid rebasing on the latest master, would you be at least open to fixing up the top-level merge commit comments?

Ok, don't worry. If this is the policy is not a problem to do the rebase. I have just pushed a rebased version of my changes.

If you agree, we can close this PR and continue in the other one ( https://github.com/vmtk/vmtk/pull/419 ) where I have the permission to contribute.

**Comment by lassoan** [comment]
Thank you very much. I'm closing this pull request then.

**Pull request closed without merging**
