### PR TITLE
Fix automated builds/conda recipe on linux and windows

### PR DESCRIPTION
**Pull request by ramtingh**
VMTK's CI/CD pipelines have been broken for the past couple of years. I find it much more convenient to have some automated tests, so I think I would rather work on fixing this first. Previously vmtk has used Appveyor for windows and Travis CI for linux/mac. Due to the [changes](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) in how Travis handles open source projects, I think it will be significantly easier to move everything to Appveyor. This PR disables windows builds (which weren't working anyway) and sets up automated conda package builds/tests on linux. All tests seem to [pass](https://ci.appveyor.com/project/RamtinGharleghi/vmtk/builds/40162982) with the current master branch.

Also as far as #359 is concerned, this should fix a lot of issues with the conda recipe (theoretically the built conda packages could be uploaded to the anaconda channel). It doesn't depend on anaconda.org/vmtk/vtk/ anymore, which was actually the source of a lot of VMTK issues (mainly that it was built against conda's now removed free channel and also did not specify a dependency on llvm). It's now using the vtk package from conda-forge which should be significantly more robust. However, It is still built against itk 4.13; I'll have a look into if any issues crop up with ITK 5 and with the changes introduced in #372 over the next few days.

### CODE REVIEW

**Comment by lassoan** [comment]
This looks awesome, thank you. I'm out of office until next week, but I'll have closer look at it next week.

**Comment by ramtingh** [comment]
With jcfr's changes and VTK 8.2, There are a couple of test failures related to vmtkbranchextractor. I'm inclined to blame the tests for that, it looks like it is assuming a specific order for the VTK arrays, e.g. GetArrayName(0) is expected to be CenterlineIds but CenterlineIds is now GetArrayName(1) and two other arrays have also changed position. Is there any reason to expect these arrays to have a fixed order or should I change these tests to expect arbitrary ordering?

pytest report [here](https://ci.appveyor.com/api/buildjobs/b8v33ymey9t0qupo/artifacts/pytest_report.html)

**Comment by rupertnash** [comment]
Apologies if I've been working at cross-purposes, I only just saw this PR. Please see my thread on discourse (https://discourse.slicer.org/t/build-and-release-vmtk-via-github-actions/19574/4) regarding using GitHub Actions for building releases. I'm not running the tests currently (I just need to get stuff working right now!)

**Comment by kayarre** [comment]
do these updates work with the latest changes on the master branch?

**Comment by kayarre** [comment]
> With jcfr's changes and VTK 8.2, There are a couple of test failures related to vmtkbranchextractor. I'm inclined to blame the tests for that, it looks like it is assuming a specific order for the VTK arrays, e.g. GetArrayName(0) is expected to be CenterlineIds but CenterlineIds is now GetArrayName(1) and two other arrays have also changed position. Is there any reason to expect these arrays to have a fixed order or should I change these tests to expect arbitrary ordering?
> 
> pytest report [here](https://ci.appveyor.com/api/buildjobs/b8v33ymey9t0qupo/artifacts/pytest_report.html)

I fixed these tests recently merged into master. The test should compare based on the array name not the index of the array.

**Review by lassoan — APPROVED** [review]
I cannot do an in-depth review of the changes, but since it fixes appveyor builds and adds support for recent Python and compiler versions, this looks a huge improvement over the current code.

**Pull request merged**
