### PR TITLE
feat: Add ability to filter on bright background and Cast image to float

### PR DESCRIPTION
**Pull request by kayarre**
This addresses  #243 by casting the input image to float.

There is a TODO around rescaling the input image such that data is not truncated but linearly fit to the data type to reduce the data loss.

I also added the ability to run the filter on dark objects on bright background.

This does not yet include a check in the c++ for the data type and exiting nicely

### CODE REVIEW

**Comment by rlizzo** [comment]
Hi kurt, since this is still a WIP, please ping me when you feel the PR is either ready to be merged, or at any time you would like some help. This is great!

**Review by lassoan — APPROVED** [review]
Looks good to me.

**Comment by kayarre** [comment]
Rebased to master, leaving comments about rescaling error handling to future work. considering it done.

**Comment by kayarre** [comment]
@lassoan thoughts on this one?

**Comment by kayarre** [comment]
fixed the commit message.

**Review by lassoan — APPROVED** [review]
Thank you, it all looks good now.

**Pull request merged**
